# Generated by Django 5.1.3 on 2024-11-28 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def add_default_heroes(apps, schema_editor):
    Superhero = apps.get_model('articles', 'Superhero')
    default_heroes = [
        {
            "name": "Superman",
            "identity": "Clark Kent",
            "description": "Man of Steel",
            "strength": "Super strength",
            "weakness": "Kryptonite",
            "image": "default_superheroes/superman.jpg",
        },
        {
            "name": "Batman",
            "identity": "Bruce Wayne",
            "description": "The Dark Knight",
            "strength": "Intelligence and martial arts",
            "weakness": "Human limitations",
            "image": "default_superheroes/batman.jpg",
        },
        {
            "name": "Wonder Woman",
            "identity": "Diana Prince",
            "description": "Amazonian warrior princess",
            "strength": "Super strength and combat skills",
            "weakness": "Bound by her own lasso",
            "image": "default_superheroes/wonder_woman.jpg",
        },
    ]
    for hero in default_heroes:
        Superhero.objects.create(
            name=hero["name"],
            identity=hero["identity"],
            description=hero["description"],
            strength=hero["strength"],
            weakness=hero["weakness"],
            is_default=True
        )


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_superhero'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='superhero',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(add_default_heroes),
        migrations.AlterField(
            model_name='superhero',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
