alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
envs:
- key: DISABLE_COLLECTSTATIC
  scope: RUN_AND_BUILD_TIME
  value: "1"
- key: POSTGRES_DB
  scope: RUN_AND_BUILD_TIME
  value: defaultdb
- key: POSTGRES_USER
  scope: RUN_AND_BUILD_TIME
  value: doadmin
- key: POSTGRES_PASSWORD
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: EV[1:rCeh8yply14oh1L7v0JNB/q5GPUh+dd9:tnlSbReM+ta9g6M3I0kVQ25G3jnD0RZUftMsJ07JSzq9CjnXHpGaOw==]
- key: POSTGRES_HOST
  scope: RUN_AND_BUILD_TIME
  value: db-postgresql-nyc3-32934-do-user-18245840-0.g.db.ondigitalocean.com
- key: POSTGRES_PORT
  scope: RUN_AND_BUILD_TIME
  value: "25060"
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: pythonwebapps-student-02-profile
    match:
      path:
        prefix: /static
  - component:
      name: pythonwebapps-student-02-profil2
    match:
      path:
        prefix: /
name: seashell-app
region: nyc
services:
- environment_slug: python
  github:
    branch: main
    deploy_on_push: true
    repo: perc85/PythonWebApps
  http_port: 8080
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-0.5gb
  name: pythonwebapps-student-02-profil2
  run_command: gunicorn --worker-tmp-dir /dev/shm config.wsgi
  source_dir: Student/week10/Superhero_articles
static_sites:
- environment_slug: html
  github:
    branch: main
    deploy_on_push: true
    repo: perc85/PythonWebApps
  name: pythonwebapps-student-02-profile
  source_dir: Student/week10/Superhero_articles/static