# Generated by Django 5.1.2 on 2024-10-29 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0003_superhero_user_alter_superhero_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superhero',
            name='user',
        ),
    ]
