# Generated by Django 5.1.1 on 2024-10-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='superhero',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='superhero',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
